name: Release new version


on:
  workflow_dispatch
  
  
jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
       - name: Set up JDK 11
         uses: actions/setup-java@v3
         with:
          java-version: "11"
          distribution: "adopt"
      
       - name: Set up GCC
         uses: egor-tensin/setup-gcc@v1
         with:
          version: latest
          platform: x64
      
       - name: Install libpcap dependency
         run: sudo apt-get install -y libpcap-dev
      
       - name: Build with maven
         run: mvn --batch-mode --update-snapshots package
         
       - name: Release new version
         uses: "marvinpinto/action-automatic-releases@latest"
         with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            LICENSE.txt
            *.jar