name: Release new version
run-name: New version release triggered by @${{ github.actor }}


on:
  workflow_dispatch
  
  
jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
       - uses: actions/checkout@v3
    
       - name: Set up JDK 11
         uses: actions/setup-java@v3
         with:
          java-version: "11"
          distribution: "adopt"
      
       - name: Set up GCC
         uses: egor-tensin/setup-gcc@v1
         with:
          version: latest
          platform: x64
      
       - name: Install libpcap dependency
         run: sudo apt-get install -y libpcap-dev
      
       - name: Build with maven
         run: mvn --batch-mode --update-snapshots -P updateConfigBuilder package -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
         
       - name: Generate update config.xml
         run: java -jar ./updateConfigBuilder/target/update-config-builder-jar-with-dependencies.jar
         
       - name: Release new version
         uses: "marvinpinto/action-automatic-releases@latest"
         with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          automatic_release_tag: "latest"
          title: "Release build"
          files: |
            LICENSE.txt
            updateConfigBuilder/target/config.xml
            server/target/nodeup-server*.jar
            bootstrap/target/nodeup-bootstrap*.jar